FROM hackudo:scratch

LABEL maintainer="Hackudo <hackudo@mailxy.org>"  \
			org.opencontainers.image.schema="1.0" \
		  org.opencontainers.image.authors="Hackudo <hackudo@mailxy.org>" \
		  org.opencontainers.image.title="Hackudo Alpine" \
			org.opencontainers.image.vendor="Hackudo" \
		  org.opencontainers.image.url="https://www.hackudo.com/dist/alpine" \
		  org.opencontainers.image.source="github.com:hackudo/hackudo-docker-alpine.git" \
		  org.opencontainers.image.licenses="apache-license-2.0-(apache-2.0)"